import Head from "next/head";
import { Home } from "../components";
import styles from "../styles/Home.module.css";

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tristan Guest</title>
        <meta
          name="Developer landing page"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Home />
    </div>
  );
}
