import Head from "next/head";
import { Header, Social } from "../components";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tristan Guest</title>
        <meta
          name="Developer landing page"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Social />
    </div>
  );
}
