import Head from "next/head";
import styles from "../styles/Page.module.css";
import { CardGrid } from "../components/CardGrid/CardGrid";

const projectList = [
  {
    title: "LunaOcean Data Platform",
    description:
      "Core member of a small team building the LunaOcean ocean weather app, built with TypeScript, Next.js, and a serverless backend leveraging AWS Lambda and MongoDB. This project represents the bulk of my professional software engineering work over the last 2-3 years.",
    image: {
      url: "/assets/projects-luna.png",
      alt: "Thumbnail view of the LunaOcean ocean weather app, built in part by the author",
    },
    tags: ["TypeScript", "Next.js", "MapboxGL JS", "AWS", "MongoDB", "Python"],
    link: {
      url: "https://lunaocean.app/",
      github: "https://lunaocean.app/",
    },
  },
  {
    title: "Dev Portfolio",
    description:
      "My personal landing page and portfolio site, built with TypeScript and Next.js. A place where I can try new things and share projects I've worked on. It includes a blog page leveraging MDX, though this component isn't live yet.",
    image: {
      url: "/assets/projects-tristanguest.png",
      alt: "Thumbnail view of the author's dev portfolio landing page",
    },
    tags: ["React", "Next.js", "MDX"],
    link: {
      url: "https://tristanguest.dev/",
      github: "https://github.com/tbguest/tristanguest.dev/",
    },
  },
  {
    title: "Repo Metrics",
    description:
      "A Next.js project for comparing GitHub repositories by interest and development effort metrics. Authenticated users can curate a custom list of repos, persisted in a MongoDB database. All asynchronous state is managed with useSWR.",
    image: {
      url: "/assets/projects-github.png",
      alt: "Thumbnail view of a GitHub repo statistics project page",
    },
    tags: ["Next.js", "TypeScript", "SWR", "MongoDB", "Next-Auth", "Chart.js"],
    link: {
      url: "https://repo-metrics.vercel.app/",
      github: "https://github.com/tbguest/repo-metrics/",
    },
  },
  {
    title: "Freelance Work",
    description:
      "I occasionally take on freelance projects. The linked page is a recent Next.js project built for an entrepreneur in the health and wellness field. All the site's content is served from a Prismic CMS and managed by the client.",
    image: {
      url: "/assets/projects-coaching.png",
      alt: "Thumbnail view of a coaching business page built for a client",
    },
    tags: ["Next.js", "Prismic"],
    link: {
      url: "https://wildoceancoaching.ca/",
      github: "https://github.com/tbguest/wildoceancoaching/",
    },
  },
];

export default function Projects() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tristan Guest</title>
        <meta
          name="Developer landing page"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <h1>Projects</h1>
      <CardGrid data={projectList} />
    </div>
  );
}
